import random
import logging

class Evolver:
    def __init__(self, generator):
        self.generator = generator

    def evolve(self, population, retain=0.5, crossover=0.3,
            mutation_prob=0.1, mutation_ratio=0.1):
        ''' Evolver, assumes a population sorted by best performance first '''
        # Number of key profiles from the old population that we are keeping
        retain_length = int(len(population) * retain)
        # Number of key profiles that will be generated by mixing
        # the major and minor key profiles of 2 different samples
        crossover_length = int(len(population) * crossover)

        # Initialize the parents of the new population
        new_population = population[:retain_length]

        # Crossover parents to fill some of the population
        children = []
        while len(children) < crossover_length:
            male = random.choice(new_population)
            female = random.choice(new_population)
            if male != female:
                # Child is made of the major key of
                # the male and minor key of the female
                child = male[:12] + female[12:]
                children.append(child)
        new_population.extend(children)

        # Do some mutations. Mutations consist in giving a 'fraction'
        # of the magnitude of a pitch class and give it to another pitch class
        # The fraction is defined by 'mutation_ratio', default is 10%
        for kp in new_population:
            if mutation_prob > random.random():
                pc1_index = 0
                pc2_index = 0
                mode = random.choice(['major', 'minor'])
                mode_index = 0 if mode == 'major' else 12
                while pc1_index == pc2_index:
                    pc1_index = random.randint(0, 11)
                    pc2_index = random.randint(0, 11)
                pc1_index += mode_index
                pc2_index += mode_index
                delta = kp[pc1_index] * mutation_ratio
                kp[pc1_index] -= delta
                kp[pc2_index] += delta

        # Fill the rest of the population with random key profiles
        while len(population) > len(new_population):
            kp = self.generator.generate_key_profile()
            new_population.append(kp)
        return new_population

